### ISSUE TITLE
DbUpdateException random by doing something with chapters

### ISSUE THREAD

**Issue by christopherpross** [audiamus/BookLibConnect#51]
Hey,
some times, I have to restart the conversion, the program throws a DBUpdateException. It have to something to releated with the chapters. I will post here the exceptiondetails and the log-file entry. I believe this is not enugh information, but maybe I am wrong?

`
07:01:57.011 0001 [BookLibrary.UpdateLicenseAndChapters] Id=323, "myAwesomeBookTitle": license_granted, throwing
DbUpdateException: "An error occurred while updating the entries. See the inner exception for details.")
************** Exceptiontext **************
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: ChapterInfos.Id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

`

**Comment by audiamus** [comment]
Yes, I need more information, the log file and also the license response json file for that book. You can upload the files here, or, for privacy reasons, send them to me as attachment via personal message on reddit.com. My user name on reddit is also audiamus.
